### PR TITLE
feat(langs): prepared for Germanic lang.

### PR DESCRIPTION
**Pull request by yehorovye**

### CODE REVIEW

**Review by uSebazz — COMMENTED** [review]
Well, is everything okay?

**Comment by yehorovye** [comment]
missing 1 file but, yea

**Comment by uSebazz** [comment]
> missing 1 file but, yea

Hmm
imagen

**Comment by uSebazz** [comment]
**I leave you something to add:**

 * create the lang variable in the command
 * add the german in the `language` command
 * correct some translations

### anything else you mention me

**Review by uSebazz — APPROVED** [review]

**Comment by uSebazz** [comment]
Create a `commands/util.json` and i push it

**Review by uSebazz — CHANGES_REQUESTED** [review]
remove it

**Review by uSebazz — CHANGES_REQUESTED** [review]
Util antiguo

**Comment by yehorovye** [comment]
q pasa

**Comment by yehorovye** [comment]
q pasa

**Comment by uSebazz** [comment]
tienes un `commands/util.json` antiguo, usa el nuevo y elimina el pequeño code que tienes en el stats.ts, eso yo lo agregue

**Comment by yehorovye** [comment]
Should be finished now.

Edit: No cuz my bro decided to fuck it all xD

**Review by uSebazz — APPROVED** [review]

**Pull request merged**
