### PR TITLE
feat(langs): added french lang.

### PR DESCRIPTION
**Pull request by simonetx**

### CODE REVIEW

**Comment by simonetx** [comment]
LMAOOO I FORGOT THE QUOTES

**Comment by simonetx** [comment]
finished ^^

**Review by hyduez — APPROVED** [review]

**Review by hyduez — APPROVED** [review]

**Review by hyduez — APPROVED** [review]

**Review by hyduez — APPROVED** [review]

**Review by hyduez — APPROVED** [review]

**Review by hyduez — APPROVED** [review]

**Review by hyduez — APPROVED** [review]

**Review by uSebazz — CHANGES_REQUESTED** [review]
Emoji incorrect

**Comment by simonetx** [comment]
yep, sorry

**Review by uSebazz — APPROVED** [review]
fine

**Comment by uSebazz** [comment]
can you fix the conflict?

**Review by hyduez — DISMISSED** [review]
~~the flag for french is german~~

srry

**Review by uSebazz — APPROVED** [review]
fine, now merge it

**Pull request merged**
