### PR TITLE
Code Style

### PR DESCRIPTION
**Pull request by hyduez**
add a malicious code over there, it gives excitement to the bot

### CODE REVIEW

**Comment by uSebazz** [comment]
Hyduez you're best

**Comment by uSebazz** [comment]
I have a question why did you remove the prettier?

**Comment by uSebazz** [comment]
I have a question why did you remove the prettier?

**Comment by hyduez** [comment]
> I have a question why did you remove the prettier?

Because I think eslint meets what is necessary. It helps to mark the style of the code, using its rules and external plugins that you can add; like typescript-eslint, templates created by the community. Also eslint is intended only for JS, while prettier is a multilanguage code formatter 
 

Ok no problem, then another question, if you remove the prettier you would have to configure the eslint correctly, which was already done. Why did you decide to change it?

**Comment by simonetx** [comment]
prisma per default is in normal deps, why u changed to dev?

**Comment by hyduez** [comment]
> prisma per default is in normal deps, why u changed to dev?

Because it is the Prisma cli, the prisma client is another dep. Also I have not seen it required in the code, so I think it is appropriate to place it as a development dep. 

If I'm wrong no problem at all let me know, I've never used prisma, so I'm totally unaware of the required modules and how they work.

**Comment by simonetx** [comment]
I use prisma, and it should be in normal deps, also it's required [here](https://github.com/uSebazz/Nino/blob/dev/src/lib/structures/NinoClient.ts#L4)

Edit: It's not the cli, as i know, sebazz used npx cli, so the dep isn't cli (prisma cli should be installed as global)

**Review by uSebazz — APPROVED** [review]
Good

**Pull request merged**
